name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Install dependencies
      run: npm ci
    - name: Run the build
      run: npm run build
    - name: Upload RELEASE
      uses: mccxiv/upload-release-action@e47ba41cb8324f54d059581734893b40f023f70e
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: _dist/*
        tag: ${{ github.ref }}
        file_glob: true
        draft: true
